import { test, expect } from '@playwright/test'
test('owner completes a shift, POS sale, receipt, and reversal through UI',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');await page.getByLabel('Alamat email').fill('owner@aspsmart.local');await page.getByLabel('Kata sandi',{exact:true}).fill('Owner123!');await page.getByRole('button',{name:'Masuk ke dashboard'}).click();await expect(page.getByRole('heading',{name:/Selamat datang,/})).toBeVisible();
 await page.goto('/app/cashier-sessions');await page.locator('table, .empty').first().waitFor();const closeExisting=page.getByRole('button',{name:'Tutup shift',exact:true});
 if(await closeExisting.count()===0){await page.getByRole('button',{name:'Buka shift'}).click();await page.getByRole('dialog').getByRole('combobox').click();await page.getByRole('button',{name:'Kas Counter',exact:false}).click();await page.getByRole('button',{name:'Simpan',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
 await page.goto('/app/pos');await page.getByRole('button',{name:/USB Cable/}).click();await page.getByRole('combobox',{name:'Rekening pembayaran'}).click();await page.getByRole('button',{name:'Kas Counter',exact:false}).click();await page.getByLabel('Uang diterima').fill('50000');await page.getByRole('button',{name:'Bayar & simpan'}).click();await expect(page).toHaveURL(/\/app\/transactions\/\d+/);await expect(page.locator('.receipt')).toContainText('USB Cable');await expect(page.locator('.receipt')).toContainText('Rp 25.000');
 await page.getByLabel('Alasan',{exact:true}).fill('QA browser: pembalikan penjualan pengujian');await page.getByRole('button',{name:'Ajukan pembalikan'}).click();await page.getByRole('button',{name:'Ya, lanjutkan'}).click();await expect(page.locator('.page-heading')).toContainText('Dibalik');
 await page.screenshot({path:'test-results/receipt-reversal.png',fullPage:true});expect(errors).toEqual([]);
});
test('financial account form persists and edits an empty QA account',async({page})=>{
 await page.goto('/login');await page.getByLabel('Alamat email').fill('owner@aspsmart.local');await page.getByLabel('Kata sandi',{exact:true}).fill('Owner123!');await page.getByRole('button',{name:'Masuk ke dashboard'}).click();await expect(page.getByRole('heading',{name:/Selamat datang,/})).toBeVisible();
 await page.goto('/app/manage/financial-accounts');await page.getByRole('button',{name:'Tambah data'}).click();const dialog=page.getByRole('dialog');const code=`QA${Date.now()}`;await dialog.getByLabel('Kode rekening').fill(code);await dialog.getByLabel('Nama rekening').fill('QA rekening kosong');await dialog.getByRole('combobox',{name:'Jenis',exact:true}).selectOption('bank');await dialog.getByLabel('Nomor rekening').fill('1234567890');await dialog.getByRole('button',{name:'Simpan data'}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('table')).toContainText(code);await expect(page.locator('table')).toContainText('******7890');
 await page.locator('tr').filter({hasText:code}).getByRole('button',{name:/Lihat nomor/}).click();await expect(dialog).toContainText('1234567890');await dialog.getByRole('button',{name:'Tutup',exact:true}).click();
 await page.locator('tr').filter({hasText:code}).getByRole('button',{name:/Edit/}).click();await dialog.getByLabel('Nama rekening').fill('QA rekening terverifikasi');await dialog.getByLabel('Aktif',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Simpan data'}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('tr').filter({hasText:code})).toContainText('QA rekening terverifikasi');
});
