import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { ArrowRight, ShieldCheck, Eye, EyeOff } from 'lucide-react'
import { toast } from 'sonner'
import { api, csrf } from '../api/axios'
import { useApp } from '../stores/app'
import { Button, Field } from '../components/ui'
export default function Auth({mode='login'}) {
 const [params]=useSearchParams(),navigate=useNavigate(),client=useQueryClient(),setAuth=useApp(s=>s.setAuth),setBranch=useApp(s=>s.setBranch),[show,setShow]=useState(false)
 const site=useQuery({queryKey:['public'],queryFn:()=>api.get('/public/website').then(r=>r.data)})
 const schema=z.object({email:z.string().email('Masukkan email yang valid.'),...(mode!=='forgot'?{password:z.string().min(mode==='reset'?10:1,'Masukkan kata sandi.')}:{}),...(mode==='reset'?{password_confirmation:z.string().min(10)}:{})})
 const {register,handleSubmit,formState:{errors}}=useForm({resolver:zodResolver(schema),defaultValues:{email:params.get('email')||''}})
 const login=useMutation({mutationFn:async d=>{await csrf();return api.post(`/auth/${mode==='login'?'login':mode==='forgot'?'forgot-password':'reset-password'}`,{...d,...(mode==='reset'?{token:params.get('token')}:{})})},onSuccess:r=>{if(mode==='login'){setAuth(r.data);setBranch(String(r.data.branches[0]?.id||''));client.setQueryData(['me'],r.data);navigate('/app')}else{toast.success(r.data.message);navigate('/login')}}})
 return <div className="auth-page"><aside className="auth-art"><Link to="/" className="brand light"><span className="brand-symbol">a<span>.</span></span><strong>{site.data?.business.name||'ASP Smart'}</strong></Link><div><span className="eyebrow">SATU SISTEM. SELURUH USAHA.</span><h1>Counter tertata.<br/>Usaha melangkah<br/><em>lebih jauh.</em></h1><p>Dari transaksi pertama hingga laporan akhir hari. Kelola usaha dengan pencatatan yang dapat Anda percaya.</p></div><div className="auth-assurance"><ShieldCheck/><span>Setiap transaksi tercatat.<br/><strong>Setiap saldo dapat ditelusuri.</strong></span></div><div className="art-circles"/></aside><main className="auth-form"><div><Link to="/" className="back-link">← Kembali ke website</Link><span className="eyebrow">RUANG KERJA COUNTER</span><h1>{mode==='login'?'Selamat datang kembali':mode==='forgot'?'Lupa kata sandi?':'Atur kata sandi baru'}</h1><p>{mode==='login'?'Masuk untuk melanjutkan aktivitas usaha Anda.':'Gunakan alamat email yang terdaftar di sistem.'}</p><form onSubmit={handleSubmit(d=>login.mutate(d))}><Field label="Alamat email" error={errors.email?.message}><input type="email" autoComplete="username" placeholder="nama@counter.com" {...register('email')}/></Field>{mode!=='forgot'&&<Field label="Kata sandi" error={errors.password?.message}><div className="password-input"><input type={show?'text':'password'} autoComplete={mode==='reset'?'new-password':'current-password'} placeholder="Masukkan kata sandi" {...register('password')}/><button type="button" onClick={()=>setShow(!show)} aria-label="Tampilkan kata sandi">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field>}{mode==='reset'&&<Field label="Ulangi kata sandi"><input type="password" {...register('password_confirmation')}/></Field>}{mode==='login'&&<Link to="/forgot-password" className="forgot-link">Lupa kata sandi?</Link>}{login.isError&&<p className="error-text" role="alert">{login.error.userMessage}</p>}<Button className="full" disabled={login.isPending}>{login.isPending?'Memproses…':mode==='login'?'Masuk ke dashboard':'Kirim'}<ArrowRight size={17}/></Button></form><div className="auth-note"><ShieldCheck size={17}/><span>Akses terbatas untuk tim yang terdaftar.</span></div></div><small>© {new Date().getFullYear()} {site.data?.business.name}</small></main></div>
}
