import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { api } from '../api/axios'
import { useApp } from '../stores/app'
import { Button, Field, State, Modal, MoneyInput, SelectResource } from '../components/ui'
import DataTable from '../components/DataTable'
import { rupiah, date } from '../utils/format'
export default function Finance({kind}) {
 const {branch}=useApp(),client=useQueryClient(),[page,setPage]=useState(1),[open,setOpen]=useState(false),[row,setRow]=useState(null),[customer,setCustomer]=useState(''),[account,setAccount]=useState(''),[amount,setAmount]=useState(''),[day,setDay]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID())
 const url=kind==='wallets'?'/wallets':kind==='daily-closings'?'/daily-closings':`/debts/${kind}`
 const q=useQuery({queryKey:[kind,branch,page],queryFn:()=>api.get(url,{params:{branch_id:branch||undefined,page}}).then(r=>r.data)})
 const title={wallets:'Wallet pelanggan',payables:'Hutang supplier',receivables:'Piutang pelanggan','daily-closings':'Penutupan harian'}[kind]
 const save=useMutation({mutationFn:()=>kind==='daily-closings'?api.post('/daily-closings',{branch_id:branch,date:day}):!row&&kind==='wallets'?api.post('/wallets',{customer_id:customer,branch_id:branch}):api.post('/transactions',{type:kind==='wallets'?'wallet_topup':kind==='payables'?'payable_payment':'receivable_payment',branch_id:row.branch_id,account_id:account,amount,idempotency_key:key,...(kind==='wallets'?{customer_id:row.customer_id,wallet_account_id:row.financial_account_id}:{settlement_of:row.id})}),onSuccess:()=>{client.invalidateQueries();setOpen(false);setRow(null);setAmount('');setKey(crypto.randomUUID());toast.success('Pencatatan berhasil disimpan.')}})
 let columns=kind==='wallets'?[{accessorKey:'customer_name',header:'Pelanggan'},{accessorKey:'branch_name',header:'Cabang'},{accessorKey:'current_balance',header:'Saldo titipan',cell:i=>rupiah(i.getValue())}]:kind==='daily-closings'?[{accessorKey:'date',header:'Tanggal'},{accessorKey:'branch_name',header:'Cabang'},{id:'count',header:'Transaksi',cell:i=>i.row.original.summary.count},{id:'revenue',header:'Pendapatan',cell:i=>rupiah(i.row.original.summary.revenue)},{id:'profit',header:'Laba',cell:i=>rupiah(i.row.original.summary.profit)}]:[{accessorKey:'reference_number',header:'Referensi'},{accessorKey:'party_name',header:kind==='payables'?'Supplier':'Pelanggan'},{accessorKey:'branch_name',header:'Cabang'},...['amount','paid_amount','outstanding_amount'].map((k,i)=>({accessorKey:k,header:['Tagihan','Dibayar','Sisa'][i],cell:r=>rupiah(r.getValue())})),{accessorKey:'created_at',header:'Tanggal',cell:i=>date(i.getValue())}]
 if(kind!=='daily-closings')columns.push({id:'action',header:'',cell:i=><Button variant="outline" onClick={()=>{setRow(i.row.original);setOpen(true)}}>{kind==='wallets'?'Top up':'Bayar tagihan'}</Button>})
 return <><div className="page-heading"><div><span className="eyebrow">KEUANGAN PELANGGAN & USAHA</span><h1>{title}</h1><p>{kind==='wallets'?'Saldo titipan terpisah dari pendapatan dan tersedia untuk pembayaran.':kind==='daily-closings'?'Ringkasan tanggal yang telah berlalu, tersimpan sebagai arsip.':'Pembayaran bertahap dengan mutasi rekening dan referensi tagihan.'}</p></div>{['wallets','daily-closings'].includes(kind)&&<Button disabled={!branch} onClick={()=>{setRow(null);setOpen(true)}}>{kind==='wallets'?'Buka wallet':'Tutup hari'}</Button>}</div>{!branch&&<div className="notice">Pilih cabang untuk membuat pencatatan baru.</div>}<div className="panel spaced"><State query={q}><DataTable columns={columns} data={q.data?.data} meta={q.data} onPage={setPage}/></State></div><Modal open={open} onOpenChange={setOpen} title={row?kind==='wallets'?'Top up wallet':'Pembayaran tagihan':kind==='wallets'?'Wallet baru':'Tutup hari'}><div className="form-grid">{kind==='daily-closings'?<Field label="Tanggal penutupan (sebelum hari ini)"><input type="date" value={day} onChange={e=>setDay(e.target.value)}/></Field>:!row?<Field label="Pelanggan"><SelectResource source="customers" value={customer} onChange={setCustomer}/></Field>:<><Field label="Rekening kas / bank"><SelectResource source="financial-accounts" branch={row.branch_id} value={account} onChange={setAccount} filter={a=>['cash','bank','ewallet'].includes(a.account_type)}/></Field><Field label="Nominal"><MoneyInput value={amount} onChange={setAmount}/></Field></>}</div><div className="form-footer"><Button disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Memproses…':'Simpan'}</Button></div></Modal></>
}
