import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { Plus, Check, X } from 'lucide-react'
import { toast } from 'sonner'
import { api } from '../api/axios'
import { useApp, allowed } from '../stores/app'
import { Button, State, Modal, Field, MoneyInput, SelectResource, Badge, Confirm } from '../components/ui'
import DataTable from '../components/DataTable'
import { rupiah, date, label } from '../utils/format'
const money=(key,title)=>({accessorKey:key,header:title,cell:i=>rupiah(i.getValue())})
const config={
 'risk-flags':{title:'Peninjauan risiko',eyebrow:'KONTROL OPERASIONAL',columns:[{accessorKey:'reference_number',header:'Referensi'},{accessorKey:'branch_name',header:'Cabang'},{accessorKey:'reason',header:'Perlu diperiksa'},{accessorKey:'status',header:'Status',cell:i=><Badge value={i.getValue()}/>},{accessorKey:'notes',header:'Hasil peninjauan'}]},
 ledger:{title:'Mutasi rekening',eyebrow:'LEDGER KEUANGAN',columns:[{id:'account',header:'Rekening',cell:i=>i.row.original.account?.name},{accessorKey:'reference_number',header:'Referensi'},{accessorKey:'direction',header:'Arah',cell:i=><Badge value={i.getValue()}/>},money('amount','Nominal'),money('balance_before','Saldo sebelum'),money('balance_after','Saldo sesudah'),{accessorKey:'created_at',header:'Waktu',cell:i=>date(i.getValue())}]},
 stock:{title:'Stok per cabang',eyebrow:'INVENTORY',columns:[{id:'product',header:'Produk',cell:i=>i.row.original.product?.name},{id:'branch',header:'Cabang',cell:i=>i.row.original.branch?.name},{accessorKey:'quantity',header:'Stok saat ini'},{id:'minimum',header:'Minimum',cell:i=>i.row.original.product?.minimum_stock}]},
 'stock-movements':{title:'Riwayat pergerakan stok',eyebrow:'INVENTORY',columns:[{accessorKey:'product_name',header:'Produk'},{accessorKey:'branch_name',header:'Cabang'},{accessorKey:'type',header:'Jenis',cell:i=>label(i.getValue())},{accessorKey:'before_qty',header:'Sebelum'},{accessorKey:'quantity',header:'Perubahan'},{accessorKey:'after_qty',header:'Sesudah'},{accessorKey:'reason',header:'Alasan'}]},
 reconciliations:{title:'Rekonsiliasi rekening',eyebrow:'KONTROL KEUANGAN',columns:[{id:'account',header:'Rekening',cell:i=>i.row.original.account?.name},money('system_balance','Saldo sistem'),money('actual_balance','Saldo aktual'),money('difference','Selisih'),{accessorKey:'status',header:'Status',cell:i=><Badge value={i.getValue()}/>},{accessorKey:'notes',header:'Catatan'}]},
 'cashier-sessions':{title:'Shift kasir',eyebrow:'OPERASIONAL',columns:[{id:'user',header:'Kasir',cell:i=>i.row.original.user?.name},{id:'account',header:'Kas',cell:i=>i.row.original.account?.name},money('opening_cash','Kas awal'),money('expected_cash','Kas sistem'),money('actual_cash','Kas hitung'),money('difference','Selisih'),{accessorKey:'closed_at',header:'Status',cell:i=>i.getValue()?'Ditutup':'Aktif'}]},
 approvals:{title:'Persetujuan transaksi',eyebrow:'KONTROL AKSES',columns:[{id:'ref',header:'Referensi',cell:i=><Link to={`/app/transactions/${i.row.original.transaction_id}`}>{i.row.original.transaction?.reference_number}</Link>},{id:'type',header:'Jenis',cell:i=>label(i.row.original.transaction?.type)},{id:'amount',header:'Nominal',cell:i=>rupiah(i.row.original.transaction?.amount)},{accessorKey:'status',header:'Status',cell:i=><Badge value={i.getValue()}/>},{accessorKey:'reason',header:'Catatan'}]},
 audit:{title:'Jejak audit',eyebrow:'AKTIVITAS SISTEM',columns:[{accessorKey:'user_name',header:'Pengguna'},{accessorKey:'action',header:'Aksi'},{accessorKey:'module',header:'Modul',cell:i=>label(i.getValue())},{accessorKey:'ip_address',header:'Alamat IP'},{accessorKey:'created_at',header:'Waktu',cell:i=>date(i.getValue())}]}
}
export default function Operations({resource}) {
 const {branch,auth}=useApp(),[page,setPage]=useState(1),[open,setOpen]=useState(false),[row,setRow]=useState(null),[account,setAccount]=useState(''),[amount,setAmount]=useState(''),[notes,setNotes]=useState(''),client=useQueryClient(),d=config[resource]
 const q=useQuery({queryKey:[resource,branch,page],queryFn:()=>api.get(`/${resource}`,{params:{branch_id:branch||undefined,page}}).then(r=>r.data)})
 const save=useMutation({mutationFn:async decision=>{if(resource==='risk-flags')return api.post(`/risk-flags/${row.id}/review`,{notes});if(resource==='reconciliations'&&row)return api.post(`/reconciliations/${row.id}/review`,{notes});if(resource==='approvals')return api.post(`/approvals/${row.id}/decision`,{approve:decision,reason:notes}); if(resource==='reconciliations')return api.post('/reconciliations',{financial_account_id:account,actual_balance:amount,notes}); return row?api.post(`/cashier-sessions/${row.id}/close`,{actual_cash:amount,notes}):api.post('/cashier-sessions',{branch_id:branch,financial_account_id:account})},onSuccess:()=>{client.invalidateQueries();setOpen(false);setRow(null);setAmount('');setNotes('');toast.success('Data berhasil disimpan.')}})
 const columns=[...d.columns]
 if((resource==='reconciliations'||resource==='risk-flags')&&allowed(auth,'approval.approve'))columns.push({id:'review',header:'',cell:({row:r})=>['pending_review','review'].includes(r.original.status)&&<Button variant="outline" onClick={()=>{setRow(r.original);setOpen(true)}}>Tinjau</Button>})
 if(resource==='cashier-sessions')columns.push({id:'action',header:'',cell:({row:r})=>!r.original.closed_at&&r.original.user_id===auth.user.id&&<Button variant="outline" onClick={()=>{setRow(r.original);setOpen(true)}}>Tutup shift</Button>})
 if(resource==='approvals')columns.push({id:'action',header:'',cell:({row:r})=>r.original.status==='pending'&&<Button variant="outline" onClick={()=>{setRow(r.original);setOpen(true)}}>Tinjau</Button>})
 return <><div className="page-heading"><div><span className="eyebrow">{d.eyebrow}</span><h1>{d.title}</h1><p>{resource==='reconciliations'?'Bandingkan saldo sistem dengan saldo sebenarnya. Selisih tidak otomatis mengubah saldo.':'Data tercatat berdasarkan aktivitas operasional usaha.'}</p></div><div className="actions">{['reconciliations','cashier-sessions'].includes(resource)&&<Button onClick={()=>{setRow(null);setOpen(true)}}><Plus size={17}/>{resource==='reconciliations'?'Rekonsiliasi baru':'Buka shift'}</Button>}{resource==='stock'&&allowed(auth,'stock.adjust')&&<Button asChild><Link to="/app/new/stock_adjustment">Opname / penyesuaian</Link></Button>}{resource==='stock'&&allowed(auth,'stock.transfer')&&<Button variant="outline" asChild><Link to="/app/stock-transfers">Transfer stok</Link></Button>}</div></div><div className="panel"><State query={q}><DataTable columns={columns} data={q.data?.data} meta={q.data} onPage={setPage}/></State></div><Modal open={open} onOpenChange={setOpen} title={resource==='approvals'?'Tinjau transaksi':row?(resource==='cashier-sessions'?'Tutup shift':'Tinjau pencatatan'):'Tambah pencatatan'}><div className="form-grid">{!['approvals','risk-flags'].includes(resource)&&!row&&<Field label="Rekening"><SelectResource source="financial-accounts" value={account} onChange={setAccount} branch={branch} filter={a=>resource!=='cashier-sessions'||a.account_type==='cash'}/></Field>}{resource==='cashier-sessions'&&!row&&<div className="notice">{branch?'Kas awal diambil dari saldo ledger rekening yang dipilih.':'Pilih cabang pada header sebelum membuka shift.'}</div>}{(resource==='reconciliations'&&!row||row&&resource==='cashier-sessions')&&<Field label="Nominal aktual hasil hitung"><MoneyInput value={amount} onChange={setAmount}/></Field>}{(row||resource==='reconciliations')&&<Field label="Catatan / alasan"><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></Field>}</div><div className="form-footer">{resource==='approvals'?<><Confirm title="Tolak transaksi?" description="Transaksi dibatalkan tanpa mutasi saldo." onConfirm={()=>save.mutate(false)}><Button variant="outline" disabled={!notes||save.isPending}><X size={16}/>Tolak</Button></Confirm><Confirm title="Setujui dan proses?" description="Server akan memeriksa saldo dan membukukan transaksi." onConfirm={()=>save.mutate(true)}><Button disabled={!notes||save.isPending}><Check size={16}/>Setujui</Button></Confirm></>:<Button disabled={save.isPending||(resource==='cashier-sessions'&&!row&&!branch)} onClick={()=>save.mutate()}>{save.isPending?'Menyimpan…':'Simpan'}</Button>}</div></Modal></>
}
