import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Download, FileText } from 'lucide-react'
import { api, download } from '../api/axios'
import { useApp, allowed } from '../stores/app'
import { Button, Field, State, SelectResource } from '../components/ui'
import DataTable from '../components/DataTable'
const snapshots=['accounts','stock','wallets']
export default function ReportCenter(){const {branch,auth}=useApp(),[dataset,setDataset]=useState('ledger'),[page,setPage]=useState(1),[from,setFrom]=useState(''),[to,setTo]=useState(''),[account,setAccount]=useState(''),[provider,setProvider]=useState(''),[busy,setBusy]=useState(false);const params={dataset,branch_id:branch||undefined,page,from:from||undefined,to:to||undefined,account_id:account||undefined,provider_id:provider||undefined};const catalog=useQuery({queryKey:['report-catalog'],queryFn:()=>api.get('/report-catalog').then(r=>r.data)}),q=useQuery({queryKey:['report-data',params],queryFn:()=>api.get('/report-data',{params}).then(r=>r.data)});const exportData=async format=>{setBusy(true);try{await download('/report-data/export',{...params,format},`${dataset}.${format}`)}finally{setBusy(false)}};return <><div className="page-heading"><div><span className="eyebrow">PUSAT LAPORAN</span><h1>Laporan operasional</h1><p>Rekening, persediaan, pelanggan, cabang, dan pengawasan.</p></div>{allowed(auth,'report.export')&&<div className="actions"><Button variant="outline" disabled={busy} onClick={()=>exportData('xlsx')}><Download size={16}/>Excel</Button><Button disabled={busy} onClick={()=>exportData('pdf')}><FileText size={16}/>PDF</Button></div>}</div><div className="panel form-panel"><div className="form-grid"><Field label="Jenis laporan"><select value={dataset} onChange={e=>{setDataset(e.target.value);setPage(1)}}>{Object.entries(catalog.data||{}).map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></Field>{!snapshots.includes(dataset)&&<><Field label="Dari tanggal"><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></Field><Field label="Sampai tanggal"><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></Field></>}{dataset==='ledger'&&<Field label="Rekening"><SelectResource source="financial-accounts" branch={branch} value={account} onChange={setAccount}/></Field>}{['digital','pulsa','data','token','ewallet'].includes(dataset)&&<Field label="Provider"><SelectResource source="providers" value={provider} onChange={setProvider}/></Field>}</div>{snapshots.includes(dataset)&&<p className="muted spaced">Laporan ini menampilkan posisi saat ini. Gunakan laporan mutasi untuk penelusuran berdasarkan periode.</p>}</div><div className="panel spaced"><div className="section-heading padded"><h2>{q.data?.title||'Memuat laporan…'}</h2></div><State query={q}><DataTable columns={Object.entries(q.data?.columns||{}).map(([key,title])=>({accessorKey:key,header:title}))} data={q.data?.rows.data} meta={q.data?.rows} onPage={setPage}/></State></div></>}
