import { useState } from 'react'
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { api } from '../api/axios'
import { Button,State,Modal,Field } from '../components/ui'
import DataTable from '../components/DataTable'
export default function Roles(){const [edit,setEdit]=useState(null),q=useQuery({queryKey:['roles'],queryFn:()=>api.get('/roles').then(r=>r.data)});return <><div className="page-heading"><div><span className="eyebrow">OTORISASI</span><h1>Role & hak akses</h1><p>Izin ditegakkan pada API dan menentukan menu yang terlihat.</p></div><Button onClick={()=>setEdit({})}>Tambah role</Button></div><div className="panel"><State query={q}><DataTable data={q.data} columns={[{accessorKey:'name',header:'Role'},{id:'count',header:'Hak akses',cell:i=>i.row.original.name==='OWNER'?'Semua akses':`${i.row.original.permissions.length} izin`},{id:'action',header:'',cell:i=>i.row.original.name!=='OWNER'&&<Button variant="outline" onClick={()=>setEdit(i.row.original)}>Atur izin</Button>}]}/></State></div><Modal open={!!edit} onOpenChange={v=>!v&&setEdit(null)} title="Hak akses role">{edit&&<RoleForm row={edit} done={()=>setEdit(null)}/>}</Modal></>}
function RoleForm({row,done}){const client=useQueryClient(),q=useQuery({queryKey:['permissions'],queryFn:()=>api.get('/permissions').then(r=>r.data)}),{register,handleSubmit}=useForm({defaultValues:{name:row.name||'',permissions:row.permissions||[]}}),save=useMutation({mutationFn:d=>row.id?api.put(`/roles/${row.id}`,d):api.post('/roles',d),onSuccess:()=>{client.invalidateQueries();toast.success('Hak akses disimpan.');done()}});return <form onSubmit={handleSubmit(d=>save.mutate(d))}><Field label="Nama role (huruf kapital)"><input required {...register('name')}/></Field><div className="checkbox-list spaced permission-list">{q.data?.map(p=><label key={p.key}><input type="checkbox" value={p.key} {...register('permissions')}/>{p.label}</label>)}</div><div className="form-footer"><Button disabled={save.isPending}>Simpan izin</Button></div></form>}
