import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { api } from '../api/axios'
import { useApp, allowed } from '../stores/app'
import { Button, Field, State, Modal, SelectResource, Badge, Confirm } from '../components/ui'
import DataTable from '../components/DataTable'
export default function StockTransfers(){
 const {branch,auth}=useApp(),client=useQueryClient(),[page,setPage]=useState(1),[open,setOpen]=useState(false),[destination,setDestination]=useState(''),[product,setProduct]=useState(''),[quantity,setQuantity]=useState('1'),[notes,setNotes]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID())
 const q=useQuery({queryKey:['stock-transfers',branch,page],queryFn:()=>api.get('/stock-transfers',{params:{branch_id:branch||undefined,page}}).then(r=>r.data)})
 const save=useMutation({mutationFn:()=>api.post('/stock-transfers',{branch_id:branch,destination_branch_id:destination,items:[{product_id:product,quantity}],notes,idempotency_key:key}),onSuccess:()=>{client.invalidateQueries();setOpen(false);setKey(crypto.randomUUID());toast.success('Draft transfer stok disimpan.')}})
 const change=useMutation({mutationFn:({id,action})=>api.post(`/stock-transfers/${id}/transition`,{action}),onSuccess:()=>{client.invalidateQueries();toast.success('Status transfer diperbarui.')}})
 const columns=[{accessorKey:'reference_number',header:'Referensi',cell:i=><Link to={`/app/transactions/${i.row.original.transaction_id}`}>{i.getValue()}</Link>},{accessorKey:'source_name',header:'Cabang sumber'},{accessorKey:'destination_name',header:'Cabang tujuan'},{accessorKey:'status',header:'Status',cell:i=><Badge value={i.getValue()}/>},{accessorKey:'notes',header:'Catatan'},{id:'action',header:'Tindakan',cell:({row})=>{const t=row.original,actions=t.status==='draft'?[...(allowed(auth,'approval.approve')?[['approve','Setujui']]:[]),['cancel','Batal']]:t.status==='approved'?[['send','Kirim barang']]:t.status==='sent'?[['receive','Terima barang']]:[];return <div className="actions">{actions.map(([action,title])=><Confirm key={action} title={`${title}?`} description={action==='send'?'Stok cabang sumber akan berkurang.':action==='receive'?'Konfirmasikan bahwa barang telah diterima; stok tujuan akan bertambah.':'Perubahan status akan dicatat dalam audit.'} onConfirm={()=>change.mutate({id:t.id,action})}><Button variant="outline" disabled={change.isPending}>{title}</Button></Confirm>)}</div>}}]
 return <><div className="page-heading"><div><span className="eyebrow">LOGISTIK ANTAR CABANG</span><h1>Transfer stok</h1><p>Draft → Disetujui → Dikirim → Diterima.</p></div><Button disabled={!branch} onClick={()=>setOpen(true)}>Transfer baru</Button></div><div className="panel"><State query={q}><DataTable columns={columns} data={q.data?.data} meta={q.data} onPage={setPage}/></State></div><Modal open={open} onOpenChange={setOpen} title="Draft transfer stok"><div className="form-grid"><Field label="Cabang tujuan"><SelectResource source="branches" value={destination} onChange={setDestination} filter={b=>String(b.id)!==String(branch)}/></Field><Field label="Produk"><SelectResource source="products" value={product} onChange={setProduct} filter={p=>p.track_stock}/></Field><Field label="Jumlah"><input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></Field><Field label="Catatan"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div><div className="form-footer"><Button disabled={save.isPending||!product||!destination||!notes} onClick={()=>save.mutate()}>Simpan draft</Button></div></Modal></>
}
