<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\FinanceController;
use App\Http\Controllers\Api\OperationController;
use App\Http\Controllers\Api\ReportCatalogController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\ResourceController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\StockOpnameController;
use App\Http\Controllers\Api\StockTransferController;
use App\Http\Controllers\Api\TransactionController;
use Illuminate\Support\Facades\Route;

Route::get('public/website', [SettingController::class, 'publicSite']);
Route::middleware('web')->group(function () {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('auth/forgot-password', [AuthController::class, 'forgot'])->middleware('throttle:5,1');
    Route::post('auth/reset-password', [AuthController::class, 'reset'])->middleware('throttle:5,1');
    Route::middleware(['auth:sanctum', 'active', 'throttle:api'])->group(function () {
        Route::get('stock-opnames', [StockOpnameController::class, 'index']);
        Route::post('stock-opnames', [StockOpnameController::class, 'store']);
        Route::post('stock-opnames/{id}/post', [StockOpnameController::class, 'post']);
        Route::post('reconciliations/{reconciliation}/review', [ReviewController::class, 'reconciliation']);
        Route::get('risk-flags', [ReviewController::class, 'riskFlags']);
        Route::post('risk-flags/{id}/review', [ReviewController::class, 'reviewRisk']);
        Route::get('accounts/{account}/reveal', [ReviewController::class, 'reveal']);
        Route::post('notifications/read', [ReviewController::class, 'readNotifications']);
        Route::get('permissions', [RoleController::class, 'permissions']);
        Route::post('roles', [RoleController::class, 'save']);
        Route::put('roles/{id}', [RoleController::class, 'save']);
        Route::get('report-catalog', [ReportCatalogController::class, 'catalog']);
        Route::get('report-data', [ReportCatalogController::class, 'index']);
        Route::get('report-data/export', [ReportCatalogController::class, 'export']);
        Route::get('stock-transfers', [StockTransferController::class, 'index']);
        Route::post('stock-transfers', [StockTransferController::class, 'store']);
        Route::post('stock-transfers/{id}/transition', [StockTransferController::class, 'transition']);
        Route::get('wallets', [FinanceController::class, 'wallets']);
        Route::post('wallets', [FinanceController::class, 'openWallet']);
        Route::get('debts/{kind}', [FinanceController::class, 'debts']);
        Route::get('daily-closings', [FinanceController::class, 'closings']);
        Route::post('daily-closings', [FinanceController::class, 'closeDay']);
        Route::get('branches/{branch}', [FinanceController::class, 'branch']);
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('metadata', [ResourceController::class, 'metadata']);
        Route::get('resources/{resource}', [ResourceController::class, 'index']);
        Route::post('resources/{resource}', [ResourceController::class, 'save']);
        Route::put('resources/{resource}/{id}', [ResourceController::class, 'save']);
        Route::get('transactions', [TransactionController::class, 'index']);
        Route::post('transactions', [TransactionController::class, 'store']);
        Route::get('transactions/{transaction}', [TransactionController::class, 'show']);
        Route::get('transactions/{transaction}/invoice', [TransactionController::class, 'invoice']);
        Route::get('ledger', [TransactionController::class, 'ledger']);
        Route::get('stock', [OperationController::class, 'stock']);
        Route::get('stock-movements', [OperationController::class, 'movements']);
        Route::get('approvals', [OperationController::class, 'approvals']);
        Route::post('approvals/{id}/decision', [OperationController::class, 'decide']);
        Route::get('cashier-sessions', [OperationController::class, 'sessions']);
        Route::post('cashier-sessions', [OperationController::class, 'open']);
        Route::post('cashier-sessions/{id}/close', [OperationController::class, 'close']);
        Route::get('reconciliations', [OperationController::class, 'reconciliations']);
        Route::post('reconciliations', [OperationController::class, 'reconcile']);
        Route::get('audit', [OperationController::class, 'audit']);
        Route::get('notifications', [OperationController::class, 'notifications']);
        Route::get('dashboard', [ReportController::class, 'dashboard']);
        Route::get('reports', [ReportController::class, 'index']);
        Route::get('reports/export', [ReportController::class, 'export']);
        Route::get('settings', [SettingController::class, 'index']);
        Route::put('settings', [SettingController::class, 'update']);
        Route::post('uploads', [SettingController::class, 'upload']);
        Route::get('users', [SettingController::class, 'users']);
        Route::post('users', [SettingController::class, 'saveUser']);
        Route::put('users/{id}', [SettingController::class, 'saveUser']);
        Route::get('roles', [SettingController::class, 'roles']);
    });
});
