<?php

use App\Models\Branch;
use App\Models\Customer;
use App\Models\DigitalProduct;
use App\Models\FinancialAccount;
use App\Models\Product;
use App\Models\Provider;
use App\Models\ProviderAccount;
use App\Models\Supplier;

// Only these explicitly registered resources are exposed to the API.
$text = fn ($label, $required = true) => ['label' => $label, 'type' => 'text', 'rules' => ($required ? 'required' : 'nullable').'|string|max:200'];
$money = fn ($label) => ['label' => $label, 'type' => 'money', 'rules' => 'required|regex:/^\d{1,14}(\.\d{1,2})?$/D'];
$select = fn ($label, $source, $required = true) => ['label' => $label, 'type' => 'select', 'source' => $source, 'rules' => ($required ? 'required' : 'nullable').'|integer|exists:'.str_replace('-', '_', $source).',id'];
$choice = fn ($label, $options) => ['label' => $label, 'type' => 'choice', 'options' => $options, 'rules' => 'required|in:'.implode(',', array_keys($options))];
$bool = fn ($label) => ['label' => $label, 'type' => 'boolean', 'rules' => 'boolean'];
$resources = [
    'branches' => ['label' => 'Cabang', 'model' => Branch::class, 'permission' => 'branch', 'fields' => ['code' => $text('Kode cabang'), 'name' => $text('Nama cabang'), 'address' => $text('Alamat', false), 'phone' => $text('Telepon', false), 'whatsapp' => $text('WhatsApp', false), 'city' => $text('Kota', false), 'is_main' => $bool('Cabang utama'), 'is_active' => $bool('Aktif')]],
    'financial-accounts' => ['label' => 'Rekening & saldo', 'model' => FinancialAccount::class, 'permission' => 'account', 'scoped' => true, 'fields' => ['branch_id' => $select('Cabang', 'branches', false), 'code' => $text('Kode rekening'), 'name' => $text('Nama rekening'), 'account_type' => $choice('Jenis', ['cash' => 'Kas', 'bank' => 'Bank', 'ewallet' => 'E-Wallet', 'provider' => 'Provider', 'central' => 'Pusat', 'other' => 'Lainnya']), 'bank_name' => $text('Nama bank', false), 'account_number' => $text('Nomor rekening', false), 'account_holder' => $text('Pemilik rekening', false), 'opening_balance' => $money('Saldo awal'), 'minimum_balance' => $money('Saldo minimum'), 'is_central' => $bool('Rekening pusat'), 'is_active' => $bool('Aktif')]],
    'customers' => ['label' => 'Pelanggan', 'model' => Customer::class, 'permission' => 'customer', 'fields' => ['code' => $text('Kode pelanggan'), 'name' => $text('Nama'), 'phone' => $text('Telepon', false), 'whatsapp' => $text('WhatsApp', false), 'email' => ['label' => 'Email', 'type' => 'email', 'rules' => 'nullable|email|max:200'], 'address' => $text('Alamat', false), 'customer_group_id' => $select('Grup', 'customer-groups', false), 'notes' => $text('Catatan', false), 'is_active' => $bool('Aktif')]],
    'suppliers' => ['label' => 'Supplier', 'model' => Supplier::class, 'permission' => 'supplier', 'fields' => ['code' => $text('Kode supplier'), 'name' => $text('Nama supplier'), 'phone' => $text('Telepon', false), 'address' => $text('Alamat', false), 'is_active' => $bool('Aktif')]],
    'providers' => ['label' => 'Provider', 'model' => Provider::class, 'permission' => 'provider', 'fields' => ['code' => $text('Kode provider'), 'name' => $text('Nama provider'), 'provider_type' => $choice('Integrasi', ['mock' => 'Mock pengembangan', 'digiflazz' => 'Digiflazz (belum terhubung)']), 'is_active' => $bool('Aktif')]],
    'provider-accounts' => ['label' => 'Akun provider', 'model' => ProviderAccount::class, 'permission' => 'provider', 'scoped' => true, 'fields' => ['branch_id' => $select('Cabang', 'branches'), 'provider_id' => $select('Provider', 'providers'), 'financial_account_id' => $select('Rekening saldo provider', 'financial-accounts'), 'account_name' => $text('Nama akun'), 'is_active' => $bool('Aktif')]],
    'digital-products' => ['label' => 'Produk digital', 'model' => DigitalProduct::class, 'permission' => 'product', 'fields' => ['provider_id' => $select('Provider', 'providers'), 'operator_id' => $select('Operator', 'operators'), 'code' => $text('Kode produk'), 'name' => $text('Nama produk'), 'category' => $choice('Kategori', ['pulsa' => 'Pulsa', 'data' => 'Paket Data', 'token' => 'Token PLN', 'ewallet' => 'E-Wallet', 'game' => 'Voucher Game', 'ppob' => 'PPOB']), 'cost_price' => $money('Harga modal'), 'selling_price' => $money('Harga jual'), 'admin_fee' => $money('Biaya admin'), 'nominal' => $money('Nominal'), 'is_active' => $bool('Aktif')]],
    'products' => ['label' => 'Produk & jasa', 'model' => Product::class, 'permission' => 'product', 'fields' => ['sku' => $text('SKU'), 'barcode' => $text('Barcode', false), 'name' => $text('Nama produk'), 'type' => $choice('Jenis', ['physical' => 'Barang fisik', 'service' => 'Jasa']), 'category_id' => $select('Kategori', 'product-categories', false), 'brand_id' => $select('Merek', 'brands', false), 'unit_id' => $select('Satuan', 'units', false), 'purchase_price' => $money('Harga modal'), 'selling_price' => $money('Harga jual'), 'track_stock' => $bool('Lacak stok'), 'minimum_stock' => ['label' => 'Stok minimum', 'type' => 'number', 'rules' => 'required|integer|min:0'], 'warranty_days' => ['label' => 'Garansi (hari)', 'type' => 'number', 'rules' => 'required|integer|min:0'], 'is_active' => $bool('Aktif')]],
    'transaction-fee-rules' => ['label' => 'Aturan biaya admin', 'permission' => 'settings', 'fields' => ['name' => $text('Nama aturan'), 'branch_id' => $select('Cabang (kosong = semua)', 'branches', false), 'type' => $choice('Transaksi', ['cash_withdrawal' => 'Tarik tunai', 'money_transfer' => 'Transfer']), 'minimum_amount' => $money('Nominal minimum'), 'maximum_amount' => ['label' => 'Nominal maksimum (opsional)', 'type' => 'money', 'rules' => 'nullable|numeric|gte:minimum_amount'], 'fee_type' => $choice('Jenis biaya', ['fixed' => 'Tetap', 'percentage' => 'Persentase']), 'fee_value' => $money('Biaya / persentase'), 'is_active' => $bool('Aktif')]],
    'branch-product-prices' => ['label' => 'Harga per cabang', 'permission' => 'product', 'scoped' => true, 'fields' => ['branch_id' => $select('Cabang', 'branches'), 'digital_product_id' => $select('Produk digital', 'digital-products'), 'selling_price' => $money('Harga jual')]],
    'website-sections' => ['label' => 'Bagian website', 'permission' => 'website', 'fields' => ['type' => $choice('Bagian', ['about' => 'Tentang', 'services' => 'Layanan', 'hours' => 'Jam buka', 'contact' => 'Kontak']), 'title' => $text('Judul'), 'subtitle' => $text('Subjudul', false), 'content' => ['label' => 'Isi', 'type' => 'textarea', 'rules' => 'nullable|string|max:10000'], 'enabled' => $bool('Tampilkan'), 'sort_order' => ['label' => 'Urutan', 'type' => 'number', 'rules' => 'required|integer|min:0|max:1000']]],
];
foreach (['customer-groups' => ['Grup pelanggan', 'customer'], 'product-categories' => ['Kategori produk', 'product'], 'brands' => ['Merek', 'product'], 'units' => ['Satuan', 'product'], 'operators' => ['Operator', 'product'], 'expense-categories' => ['Kategori pengeluaran', 'expense']] as $key => [$label,$permission]) {
    $resources[$key] = ['label' => $label, 'permission' => $permission, 'fields' => ['name' => $text('Nama'), 'is_active' => $bool('Aktif')]];
}
foreach (['galleries' => 'Galeri', 'testimonials' => 'Testimoni', 'promotions' => 'Promosi'] as $key => $label) {
    $resources[$key] = ['label' => $label, 'permission' => 'website', 'fields' => ['title' => $text('Judul'), 'description' => ['label' => 'Keterangan', 'type' => 'textarea', 'rules' => 'nullable|string|max:5000'], 'image' => ['label' => 'Gambar', 'type' => 'image', 'rules' => 'nullable|string|max:250|starts_with:/storage/uploads/'], 'is_active' => $bool('Aktif')]];
}
$resources['customer-group-prices'] = ['label' => 'Harga grup pelanggan', 'permission' => 'product', 'fields' => ['customer_group_id' => $select('Grup pelanggan', 'customer-groups'), 'digital_product_id' => $select('Produk digital', 'digital-products'), 'selling_price' => $money('Harga jual')]];
$resources['branch-group-prices'] = ['label' => 'Harga grup per cabang', 'permission' => 'product', 'scoped' => true, 'fields' => ['branch_id' => $select('Cabang', 'branches'), 'customer_group_id' => $select('Grup pelanggan', 'customer-groups'), 'digital_product_id' => $select('Produk digital', 'digital-products'), 'selling_price' => $money('Harga jual')]];
$resources['operator-prefixes'] = ['label' => 'Prefix operator', 'permission' => 'product', 'fields' => ['operator_id' => $select('Operator', 'operators'), 'prefix' => ['label' => 'Prefix nomor', 'type' => 'text', 'rules' => 'required|regex:/^0[0-9]{2,7}$/D']]];

return ['resources' => $resources];
